# Clase 6 - Preprocesamiento

## Carga de librerías

In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

## Ejercicio

In [58]:
#SE CARGAN LOS DATOS
datos = pd.read_csv("datos_procesamiento.csv")

#SE IMPRIME EL TIPO QUE TIENE LA VARIABLE DATOS
print("Tamaño=",datos.shape)
print("Tipo=",datos.dtypes)

Tamaño= (1000, 8)
Tipo= col_inexistente1    float64
col2                float64
col3                float64
col_outliers          int64
col_outliers2       float64
col_categorica       object
col_ordinal          object
col_texto            object
dtype: object


In [59]:
datos.head(5)

col_inexistente1  col2      col3  col_outliers  col_outliers2  \
0              59.0  52.0  2.232832           -50       0.771666   
1              31.0  74.0  0.906147            -5       1.068558   
2              81.0  28.0  0.626750           -32       0.846396   
3              34.0  16.0  0.816738           -84       0.637381   
4              32.0  28.0  0.571131            65       4.540614   

  col_categorica col_ordinal  \
0          ratón    muy bien   
1       elefante     regular   
2          ratón     muy mal   
3           gato         mal   
4           gato        bien   

                                           col_texto  
0  Tenía en su casa una ama que pasaba de los cua...  
1  El resto della concluían sayo de velarte, calz...  
2  El resto della concluían sayo de velarte, calz...  
3  Una olla de algo más vaca que carnero, salpicó...  
4  Tenía en su casa una ama que pasaba de los cua...

# Variables numéricas

In [60]:
#EL SIGUIENTE CODIGO SELECCIONA AQUELLOS QUE SON ENTEROS Y FLOTANTES
var_numericas_df = datos.select_dtypes([int, float])
#INGRESA LA COLUMNA QUE NO LEE
var_numericas_df["col_outliers"] = datos["col_outliers"]
print("Se imprime cabezal=",var_numericas_df.columns)

#SE PREGUNTA POR VALORES NULOS
print("Tamaño de valores nulos=",var_numericas_df[var_numericas_df.isnull().any(axis=1)].shape)
print("Los primeros valores nulos=",var_numericas_df[var_numericas_df.isnull().any(axis=1)].head())

Se imprime cabezal= Index(['col_inexistente1', 'col2', 'col3', 'col_outliers', 'col_outliers2'], dtype='object')
Tamaño de valores nulos= (96, 5)
Los primeros valores nulos=     col_inexistente1  col2      col3  col_outliers  col_outliers2
9                NaN  53.0  2.270999            62       1.067230
10               NaN  99.0  1.394209            98       4.145716
16               NaN  50.0  0.437365            59      20.549474
17               NaN  73.0  0.324893            98       0.761684
23               NaN  85.0  3.664671           -48       3.154153


## Imputador

In [61]:
#IMPUTADOR BUSCA LOS NULOS Y LOS RELLENA CON UNA ESTRATEGIA
# EN ESTE CASO LA ESTRATEGIA ES LLENARLO CON LA MEDIA
# HAY MAS ESTRATEGIAS

from sklearn.impute import SimpleImputer
imputador = SimpleImputer(missing_values=np.nan, copy=False, strategy="mean")

#SE APLICA EL IMPUTADOR A LA TABLA ORIGINAL
var_numericas_imputadas = imputador.fit_transform(var_numericas_df)

#LA TABLA IMPUTADA YA NO TIENE VALORES NULOS

#POR ULTIMO SE CONVIERTE A DATAFRAME
var_numericas_imputadas_df = pd.DataFrame(var_numericas_imputadas, index=var_numericas_df.index, columns=var_numericas_df.columns)
var_numericas_imputadas_df.head(10)

col_inexistente1  col2       col3  col_outliers  col_outliers2
0         59.000000  52.0   2.232832         -50.0       0.771666
1         31.000000  74.0   0.906147          -5.0       1.068558
2         81.000000  28.0   0.626750         -32.0       0.846396
3         34.000000  16.0   0.816738         -84.0       0.637381
4         32.000000  28.0   0.571131          65.0       4.540614
5         81.000000   4.0   1.618844          51.0       0.812940
6         57.000000  31.0   0.167880          78.0       1.235137
7         34.000000  20.0  20.229813          93.0       1.283176
8         37.000000  96.0   2.407978          54.0       1.298613
9         48.382743  53.0   2.270999          62.0       1.067230

Se comprueba que ya no existen valores nulos

In [62]:
#SE IMPRIME EL TAMAÑO DEL NUEVO DATAFRAME Y AHORA YA NO TIENE VALORES NULOS
print(var_numericas_imputadas_df[var_numericas_imputadas_df.isnull().any(axis=1)].shape)

(0, 5)


## Estandarizacion

In [63]:
#SE IMPRIME EL TAMAÑO DEL NUEVO DATAFRAME Y AHORA YA NO TIENE VALORES NULOS
print(var_numericas_imputadas_df[var_numericas_imputadas_df.isnull().any(axis=1)].shape)

#PROCESOS DE ESTANDARIZACION

#VARIABLES NUMERICAS
var_numericas_imputadas_df[var_numericas_imputadas_df.isnull().any(axis=1)].shape

#PROMEDIO DE LAS VARIABLES NUMERICAS
print(var_numericas_df.mean())

#DESVIACION ESTANDAR DE LAS VARIABLES NUMERICA
print(var_numericas_df.std())

(0, 5)
col_inexistente1     48.382743
col2                 49.660000
col3                  1.466095
col_outliers          4.253000
col_outliers2       131.193340
dtype: float64
col_inexistente1      27.987174
col2                  28.272668
col3                   1.732358
col_outliers          78.145901
col_outliers2       3401.164776
dtype: float64


Para estandarizar se aplica una nueva columna el valor menos la media y divido entre la desviacion estandar

In [64]:
escalador = preprocessing.StandardScaler()
var_numericas_imputadas_escalado_standard = escalador.fit_transform(var_numericas_imputadas)
var_numericas_imputadas_escalado_standard

array([[ 0.39921733,  0.08280686,  0.44281884, -0.69460006, -0.03836537],
       [-0.65360504,  0.86133291, -0.32339035, -0.11846597, -0.03827803],
       [ 1.22643491, -0.76649428, -0.4847522 , -0.46414642, -0.03834338],
       ...,
       [-1.10481463,  0.11819441, -0.42094381,  0.88016644, -0.03819664],
       [ 1.48964051,  1.56908386, -0.4077454 ,  0.81615154, -0.03818958],
       [ 1.7152453 ,  0.22435705, -0.13638793,  0.72653069, -0.03831468]])

In [65]:
#SI SE IMPRIMEN LAS MEDIAS NO SE PIERDEN
print("Media de la tabla estandarizada:")
print(escalador.mean_)

Media de la tabla estandarizada:
[ 48.38274336  49.66         1.46609489   4.253      131.19333968]


In [66]:
#LOS DATOS DE LAS TABLAS NUEVAS ESTANDARIZADAS
#SE COMPRUEBA QUE LAS MEDIAS DAN CERO
print(var_numericas_imputadas_escalado_standard.mean(axis=0))

#Y QUE LAS VARIANZAS DAN 1
print(var_numericas_imputadas_escalado_standard.std(axis=0))

[-5.86197757e-17  1.26121336e-16 -3.90798505e-17  3.55271368e-18
 -3.55271368e-18]
[1. 1. 1. 1. 1.]


Para aquellos casos en los que los datos tengan muchos valores extremos, es posible que estandarizar usando la media y la desviacion estandar no funcione bien en el modelo. 

Para esos casos es mejor usar unos estimadores mas robustos (menos sensibles a outliers) y emplear un RobustScaler que funciona substrayendo la mediana y escalando mediante el rango intercuartil (IQR).

**LA TRANSFORMACION DE DATOS SIRVE PARA DISMINUIR LOS OUTLIERS EN CASO DE QUE TENGAN MUCHOS DATOS ATIPICOS ES MEJOR USAR ESTIMULADORES MAS ROBUSTOS**

**Escalador Robusto**

In [67]:
escalador_robusto = preprocessing.RobustScaler()
var_numericas_imputadas_escalado_robusto = escalador_robusto.fit_transform(var_numericas_imputadas)

#LAS MEDIAS CAMBIAN CON UN ESCALADOR ROBUSTO
print(var_numericas_imputadas_escalado_robusto.mean(axis=0))

#LAS VARIANZAS TAMBIEN CAMBIAN
print(var_numericas_imputadas_escalado_robusto.std(axis=0))

#LOS ESCALADORES QUITAN UNIDADES, LA ESTANDAR Y LA ROBUSTA QUITAN LAS UNIDADES, NO TODAS LO HACEN

[-3.81916720e-17 -2.85106383e-02  4.01958704e-01  3.04018692e-02
  7.03130782e+01]
[6.33218559e-01 6.01245275e-01 1.38651621e+00 7.29970260e-01
 1.83690817e+03]


**Escalado a un rango especifico**

Hay casos en los que en vez de estandardizar queremos escalar los datos a un rango (generalmente [-1,1] o [0,1]). Para ello podemos usar MinMaxScaler que hace escalado minmax (obviamente) o MaxAbscaler que simplemente divide cada valor de una variable por su valor máximo (y por tanto convierte el valor maximo a 1).

In [68]:
escalador_minmax = preprocessing.MinMaxScaler()
var_numericas_imputadas_escalado_minmax = escalador_minmax.fit_transform(var_numericas_imputadas)
var_numericas_imputadas_escalado_minmax

array([[5.95959596e-01, 5.25252525e-01, 8.49335896e-02, 5.04540868e-02,
        2.00220676e-04],
       [3.13131313e-01, 7.47474747e-01, 3.33576826e-02, 9.58627649e-02,
        2.02985584e-04],
       [8.18181818e-01, 2.82828283e-01, 2.24959182e-02, 6.86175580e-02,
        2.00916618e-04],
       ...,
       [1.91919192e-01, 5.35353535e-01, 2.67910580e-02, 1.74571140e-01,
        2.05562389e-04],
       [8.88888889e-01, 9.49494949e-01, 2.76794836e-02, 1.69525732e-01,
        2.05785844e-04],
       [9.49494949e-01, 5.65656566e-01, 4.59453931e-02, 1.62462159e-01,
        2.01825192e-04]])

In [69]:
#LOS VALORES MAXIMOS Y MINIMOS SON 1 Y 0
print(var_numericas_imputadas_escalado_minmax.max())
print(var_numericas_imputadas_escalado_minmax.min())

1.0000000000000002
0.0


**Escalado MaxAbsScaler**

In [70]:
#EL ESCALADOR MAXABSSCALER LOS DIVIDE ENTRE EL VALOR MAS GRANDE
escalador_maxabs = preprocessing.MaxAbsScaler()
var_numericas_imputadas_escalado_maxabs = escalador_maxabs.fit_transform(var_numericas_imputadas)
var_numericas_imputadas_escalado_maxabs

array([[ 5.95959596e-01,  5.25252525e-01,  8.66411060e-02,
        -5.61167228e-02,  7.18779671e-06],
       [ 3.13131313e-01,  7.47474747e-01,  3.51614398e-02,
        -5.61167228e-03,  9.95323866e-06],
       [ 8.18181818e-01,  2.82828283e-01,  2.43199434e-02,
        -3.59147026e-02,  7.88387337e-06],
       ...,
       [ 1.91919192e-01,  5.35353535e-01,  2.86070685e-02,
         8.19304153e-02,  1.25305407e-05],
       [ 8.88888889e-01,  9.49494949e-01,  2.94938363e-02,
         7.63187430e-02,  1.27540390e-05],
       [ 9.49494949e-01,  5.65656566e-01,  4.77256616e-02,
         6.84624018e-02,  8.79262270e-06]])

In [71]:
#EL VALOR MAXIMO ES 1
print(var_numericas_imputadas_escalado_maxabs.max())
#EL MINIMO ES EL MENOR VALOR DIVIDIDO ENTRE EL MAYOR
print(var_numericas_imputadas_escalado_maxabs.min())

1.0
-0.1122334455667789


**Normalizer**

In [72]:
#Hay casos en los que lo que se necesita es tener observaciones con norma unitaria 
#(norma L2 o euclidiana). Para esos casos, podemos usar Normalizer

normalizador = preprocessing.Normalizer()
var_numericas_imputadas_normal = normalizador.fit_transform(var_numericas_imputadas)

In [73]:
#Hay que tener en cuenta que el objetivo del Normalizer es normalizar casos,
# no variables (o sea que funciona por filas)

print(var_numericas_imputadas_normal[1,:])
print(np.linalg.norm(var_numericas_imputadas_normal[1,:]))

[ 0.38557802  0.92041204  0.01127066 -0.06219     0.01329073]
1.0


In [74]:
#Hay que tener en cuenta que el objetivo del Normalizer es normalizar casos,
# no variables (o sea que funciona por filas)

print(var_numericas_imputadas_normal[1,:])
print(np.linalg.norm(var_numericas_imputadas_normal[1,:]))

[ 0.38557802  0.92041204  0.01127066 -0.06219     0.01329073]
1.0


# Variables categoricas

Los modelos están diseñados para trabajar con variables numéricas. Esto implica que para poder entrenar los modelos con variables categóricas tenemos que convertirlas a números.Este proceso se llama codificación (encoding)


In [75]:
datos = pd.read_csv("datos_procesamiento.csv")
var_categoricas = datos[['col_categorica', 'col_ordinal']]
var_categoricas

col_categorica col_ordinal
0            ratón    muy bien
1         elefante     regular
2            ratón     muy mal
3             gato         mal
4             gato        bien
..             ...         ...
995       elefante     muy mal
996          ratón    muy bien
997       elefante     regular
998       elefante        bien
999       elefante     regular

[1000 rows x 2 columns]

Hay muchas formas de codificar variables, la más sencilla es reemplazar los elementos de dichas variables por un número. Por ejemplo, si hacemos esto con la columna col_ordinal:

In [76]:
label_codificador = preprocessing.LabelEncoder()
label_codificador.fit(datos.col_ordinal)
print(label_codificador.classes_)

['bien' 'mal' 'muy bien' 'muy mal' 'regular']


**Transform**

In [77]:
#TRANSFORM
label_codificador.transform(['muy bien', 'muy mal', 'muy bien', 'muy mal', 'bien'])

array([2, 3, 2, 3, 0])

In [78]:
label_codificador.inverse_transform([0, 0, 1, 2])


array(['bien', 'bien', 'mal', 'muy bien'], dtype=object)

En el caso de variables ordinales esto tiene sentido ya que muy_bien>bien>regular>mal>muy mal.

Sin embargo, esto indica a los modelos de scikit-learn por ejemplo que mal + regular = bien.

Esto se puede usar en según que casos (hay modelos que no interpretan las variables numéricas así), o para codificar las variables objetivo.

In [79]:
#Para variables categóricas (por ejemplo animales) no tiene sentido usar este tipo de encoding.

label_codificador_categorico = preprocessing.LabelEncoder()
label_codificador_categorico.fit_transform(datos.col_categorica)[:10]

print(label_codificador_categorico.classes_)

['elefante' 'gato' 'perro' 'ratón']


Digamos que no tiene sentido decir que la media de elefante y perro no es gato.

Para estos casos una técnica que se puede usar se llama one-hot encoding. 

Lo que significa es que creamos n columnas binarias, con el valor 0 por defecto salvo la columna referente a la observación.

**One HotEncoder**

Vemos que OneHotEncoder falla cuando se le pasan strings en vez de numeros.

Por ello primero tenemos que convertir las variables categóricas a numéricas usando LabelEncoder.

In [80]:
oh_codificador = preprocessing.OneHotEncoder()

In [81]:
categorias_codificadas = label_codificador_categorico.transform(datos.col_categorica)

categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))
print(categorias_oh_codificadas.toarray())

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


Vemos ahora la comparación en memoria de una matriz sparse versus su correspondiente np.array usando la función sys.getsizeof que devuelve el uso de memoria un objeto de python en bytes.

In [82]:
import sys

#PREGUNTAMOS CUANTO MIDE LA MATRIZ ESCASA
print(sys.getsizeof(categorias_oh_codificadas))

print(sys.getsizeof(categorias_oh_codificadas.toarray()))

48
32128


SI QUEREMOS QUE EL ENCODER DEVUELVA ARRAYS NO TENEMOS MAS QUE PASARLE EL PARAMETRO sparse = False

In [83]:
oh_codificador = preprocessing.OneHotEncoder(sparse=False)
categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))
print(categorias_oh_codificadas)

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [84]:
#PANDAS TIENE LA FUNCION AUXILIAR get_dummies QUE HACE ESTO AUTOMATICAMENTE DE FORMA MAS FACIL
print(pd.get_dummies(datos.col_categorica).head())
#SE DICE QUE ESTO ES UN PROCEDIMIENTO PARA CONVERTIR A VARIABLES DUMMIES

   elefante  gato  perro  ratón
0         0     0      0      1
1         1     0      0      0
2         0     0      0      1
3         0     1      0      0
4         0     1      0      0


# Variable tipo texto

Columnas de texto

In [85]:
from sklearn import feature_extraction
#LOS PRIMERO 10 RENGLONES
print(datos.col_texto.values[:10])

['Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.'
 'El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino.'
 'El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino.'
 'Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda.'
 'Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.'
 'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiem

PARA CONVERTIR TEXTO EN VARIABLES NUMERICAS, PODEMOS PROCEDER DE IGUAL
FORMA QUE CON LAS VARIABLES CATEGORICAS, SIMPLEMENTE SEPARANDO LAS PALABRAS ANTES PARA ELLOS TENEMOS DOS VECTORIZADORES EN scikit-learn, QUE CONVIERTEN TEXTO EN VECTORES

**CountVectorizer** DEVUELVE UN VECTOR CON EL VALOR 0 EN TODAS LAS PALABRAS QUE NO EXISTEN EN UNA FRASE Y CON EL NUMERO DE OCURRENCIAS DE LAS PALABRAS QUE SI EXISTEN

In [86]:
ejemplo_frases = ['los coches rojos',
          'los aviones son rojos',
          'los coches y los aviones son rojos',
          'los camiones rojos'
                 ]

vectorizador_count = feature_extraction.text.CountVectorizer()
X = vectorizador_count.fit_transform(ejemplo_frases)
print(X) #SUELTA UNA MATRIZ ESCASA

#SE IMPRIMEN TODAS LAS PALABRAS QUE EXISTEN O TOMO EN CUENTA
vectorizador_count.get_feature_names()

  (0, 3)	1
  (0, 2)	1
  (0, 4)	1
  (1, 3)	1
  (1, 4)	1
  (1, 0)	1
  (1, 5)	1
  (2, 3)	2
  (2, 2)	1
  (2, 4)	1
  (2, 0)	1
  (2, 5)	1
  (3, 3)	1
  (3, 4)	1
  (3, 1)	1


c:\Users\felip\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aviones', 'camiones', 'coches', 'los', 'rojos', 'son']

POR ULTIMO SE MUESTRA EN UN DATAFRAME LA INFORMACION DONDE CADA COLUMNA CONTIENE UNA PALABRA Y EN CADA RENGLON SE MUESTRA EL VALOR QUE LE DIO POR LA PALABRA QUE APARECE

In [87]:
eg_4frases = pd.DataFrame(X.toarray(), columns=vectorizador_count.get_feature_names_out());
eg_4frases

aviones  camiones  coches  los  rojos  son
0        0         0       1    1      1    0
1        1         0       0    1      1    1
2        1         0       1    2      1    1
3        0         1       0    1      1    0

SE UTILIZA OTRO TIPO DE TRANSFORMACION, PARA PODER DARLE VALOR AL APARECIMIENTO DE LAS PALABRAS

El tomar simplemente el número de veces que aparece cada palabra tiene un problema, y es que da un mayor peso a aquellas palabras que aparecen muchas veces pero que no aportan ningun valor semántico (por ejemplo, los). Una manera más sofisticada de vectorizar 
#un texto es en vez de usar el número de apariciones, usar TF-IDF. TF-IDF se traduce como Frecuencia de Texto - Frecuencia Inversa de Documento, y es una medida que asigna pesos a cada palabra en función de su frecuencia de aparición en todos los documents.

In [88]:
#SE APLICA EL TF IDF PARA EL EJEMPLO DE LAS 4 FRASES
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
X = vectorizador_tfidf.fit_transform(ejemplo_frases)
eg_4frasesTFID = pd.DataFrame(X.toarray(), columns=vectorizador_tfidf.get_feature_names_out())
eg_4frasesTFID

aviones  camiones    coches       los     rojos       son
0  0.000000  0.000000  0.730064  0.483222  0.483222  0.000000
1  0.589645  0.000000  0.000000  0.390280  0.390280  0.589645
2  0.438931  0.000000  0.438931  0.581047  0.290524  0.438931
3  0.000000  0.804612  0.000000  0.419880  0.419880  0.000000

In [89]:
#AQUI SE APLICA PARA TODAS LAS FRASES DE LA TABLA ORIGINAL
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
texto_vectorizado = vectorizador_tfidf.fit_transform(datos.col_texto)
print(texto_vectorizado)

texto_vectorizado = texto_vectorizado.toarray()
print(texto_vectorizado)

  (0, 94)	0.20474512283483218
  (0, 65)	0.10065821409936059
  (0, 121)	0.20474512283483218
  (0, 23)	0.20474512283483218
  (0, 106)	0.15034557766259068
  (0, 44)	0.12243161910832584
  (0, 47)	0.20474512283483218
  (0, 9)	0.20474512283483218
  (0, 92)	0.20474512283483218
  (0, 16)	0.20474512283483218
  (0, 77)	0.20474512283483218
  (0, 123)	0.12073232918524478
  (0, 126)	0.20474512283483218
  (0, 70)	0.20474512283483218
  (0, 81)	0.12073232918524478
  (0, 115)	0.20474512283483218
  (0, 30)	0.20474512283483218
  (0, 72)	0.14641557448062523
  (0, 33)	0.14641557448062523
  (0, 90)	0.20474512283483218
  (0, 97)	0.30944223132071785
  (0, 5)	0.20474512283483218
  (0, 124)	0.3189890228844466
  (0, 19)	0.20474512283483218
  (0, 116)	0.12716589297374567
  :	:
  (999, 121)	0.20474512283483218
  (999, 23)	0.20474512283483218
  (999, 106)	0.15034557766259068
  (999, 44)	0.12243161910832584
  (999, 47)	0.20474512283483218
  (999, 9)	0.20474512283483218
  (999, 92)	0.20474512283483218
  (999, 16)	0.2

# Aplicando transformaciones de manera rapida

In [90]:
# Seleccion de columnas
col_numericas =  ['col_inexistente1', 'col2', 'col3', 'col_outliers', 'col_outliers2']
col_categorica = ['col_categorica']
col_texto = ['col_texto']

### Variables numericas

In [91]:
# Clases de preprocesamiento
imputador = SimpleImputer(missing_values=np.nan, copy=False, strategy="mean")
escalador = preprocessing.StandardScaler()
# Se aplica el preprocesamiento
var_numericas_imputadas_escalado_standard = escalador.fit_transform(imputador.fit_transform(datos[col_numericas]))
df_numerico_procesado = pd.DataFrame(var_numericas_imputadas_escalado_standard, columns=col_numericas)
df_numerico_procesado

col_inexistente1      col2      col3  col_outliers  col_outliers2
0            0.399217  0.082807  0.442819     -0.694600      -0.038365
1           -0.653605  0.861333 -0.323390     -0.118466      -0.038278
2            1.226435 -0.766494 -0.484752     -0.464146      -0.038343
3           -0.540803 -1.191145 -0.375028     -1.129901      -0.038405
4           -0.616004 -0.766494 -0.516874      0.777743      -0.037257
..                ...       ...       ...           ...            ...
995          1.376838  0.365907  0.492254      0.611304      -0.038492
996         -0.352799 -1.615795  0.131503      0.700925      -0.037878
997         -1.104815  0.118194 -0.420944      0.880166      -0.038197
998          1.489641  1.569084 -0.407745      0.816152      -0.038190
999          1.715245  0.224357 -0.136388      0.726531      -0.038315

[1000 rows x 5 columns]

### Variables categoricas

In [92]:
# Se plaica el Label Encoder
label_codificador_categorico = preprocessing.LabelEncoder()
categorias_codificadas = label_codificador_categorico.fit_transform(datos[col_categorica])
# Se aplica el OneHot Encoder
oh_codificador = preprocessing.OneHotEncoder(sparse=False)
categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))
# Se junta todo el procesamiento
df_categorico_procesado = pd.DataFrame(categorias_oh_codificadas, 
                                       columns=label_codificador_categorico.classes_)
df_categorico_procesado


c:\Users\felip\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


elefante  gato  perro  ratón
0         0.0   0.0    0.0    1.0
1         1.0   0.0    0.0    0.0
2         0.0   0.0    0.0    1.0
3         0.0   1.0    0.0    0.0
4         0.0   1.0    0.0    0.0
..        ...   ...    ...    ...
995       1.0   0.0    0.0    0.0
996       0.0   0.0    0.0    1.0
997       1.0   0.0    0.0    0.0
998       1.0   0.0    0.0    0.0
999       1.0   0.0    0.0    0.0

[1000 rows x 4 columns]

### Variable tipo texto

In [93]:
# Texto
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
texto_vectorizado = vectorizador_tfidf.fit_transform(datos.col_texto)
df_texto_procesado =  pd.DataFrame(texto_vectorizado.toarray(), columns=vectorizador_tfidf.get_feature_names_out())
df_texto_procesado

acordarme    adarga      algo  alguna     algún       ama     amigo  \
0     0.000000  0.000000  0.000000     0.0  0.000000  0.204745  0.000000   
1     0.000000  0.000000  0.000000     0.0  0.000000  0.000000  0.000000   
2     0.000000  0.000000  0.000000     0.0  0.000000  0.000000  0.000000   
3     0.000000  0.000000  0.194272     0.0  0.194272  0.000000  0.000000   
4     0.000000  0.000000  0.000000     0.0  0.000000  0.204745  0.000000   
..         ...       ...       ...     ...       ...       ...       ...   
995   0.000000  0.000000  0.000000     0.0  0.000000  0.000000  0.218526   
996   0.000000  0.000000  0.000000     0.0  0.000000  0.204745  0.000000   
997   0.000000  0.000000  0.000000     0.0  0.000000  0.000000  0.000000   
998   0.197887  0.197887  0.000000     0.0  0.000000  0.000000  0.000000   
999   0.000000  0.000000  0.000000     0.0  0.000000  0.204745  0.000000   

      antigua  astillero       así  ...       una      vaca    veinte  \
0    0.000000   0.000000  0.204745  ...  0.318989  0.000000  0.204745   
1    0.000000   0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2    0.000000   0.000000  0.000000  ...  0.000000  0.000000  0.000000   
3    0.000000   0.000000  0.000000  ...  0.143675  0.194272  0.000000   
4    0.000000   0.000000  0.204745  ...  0.318989  0.000000  0.204745   
..        ...        ...       ...  ...       ...       ...       ...   
995  0.000000   0.000000  0.000000  ...  0.000000  0.000000  0.000000   
996  0.000000   0.000000  0.204745  ...  0.318989  0.000000  0.204745   
997  0.000000   0.000000  0.000000  ...  0.000000  0.000000  0.000000   
998  0.197887   0.197887  0.000000  ...  0.000000  0.000000  0.000000   
999  0.000000   0.000000  0.204745  ...  0.318989  0.000000  0.204745   

      velarte   vellori   velludo  verdad  verosímiles   viernes     vivía  
0    0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000  
1    0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000  
2    0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000  
3    0.000000  0.000000  0.000000     0.0          0.0  0.194272  0.000000  
4    0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000  
..        ...       ...       ...     ...          ...       ...       ...  
995  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000  
996  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000  
997  0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000  
998  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.197887  
999  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000  

[1000 rows x 134 columns]

Se concatenan los datos procesados

In [94]:
#SE CONCATENAN LOS DATOS PROCESADOS
datos_procesados = pd.concat([
    df_numerico_procesado,
    df_categorico_procesado,
    df_texto_procesado 
], axis=1)
datos_procesados

col_inexistente1      col2      col3  col_outliers  col_outliers2  \
0            0.399217  0.082807  0.442819     -0.694600      -0.038365   
1           -0.653605  0.861333 -0.323390     -0.118466      -0.038278   
2            1.226435 -0.766494 -0.484752     -0.464146      -0.038343   
3           -0.540803 -1.191145 -0.375028     -1.129901      -0.038405   
4           -0.616004 -0.766494 -0.516874      0.777743      -0.037257   
..                ...       ...       ...           ...            ...   
995          1.376838  0.365907  0.492254      0.611304      -0.038492   
996         -0.352799 -1.615795  0.131503      0.700925      -0.037878   
997         -1.104815  0.118194 -0.420944      0.880166      -0.038197   
998          1.489641  1.569084 -0.407745      0.816152      -0.038190   
999          1.715245  0.224357 -0.136388      0.726531      -0.038315   

     elefante  gato  perro  ratón  acordarme  ...       una      vaca  \
0         0.0   0.0    0.0    1.0   0.000000  ...  0.318989  0.000000   
1         1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
2         0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.000000   
3         0.0   1.0    0.0    0.0   0.000000  ...  0.143675  0.194272   
4         0.0   1.0    0.0    0.0   0.000000  ...  0.318989  0.000000   
..        ...   ...    ...    ...        ...  ...       ...       ...   
995       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
996       0.0   0.0    0.0    1.0   0.000000  ...  0.318989  0.000000   
997       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
998       1.0   0.0    0.0    0.0   0.197887  ...  0.000000  0.000000   
999       1.0   0.0    0.0    0.0   0.000000  ...  0.318989  0.000000   

       veinte   velarte   vellori   velludo  verdad  verosímiles   viernes  \
0    0.204745  0.000000  0.000000  0.000000     0.0          0.0  0.000000   
1    0.000000  0.181842  0.181842  0.181842     0.0          0.0  0.000000   
2    0.000000  0.181842  0.181842  0.181842     0.0          0.0  0.000000   
3    0.000000  0.000000  0.000000  0.000000     0.0          0.0  0.194272   
4    0.204745  0.000000  0.000000  0.000000     0.0          0.0  0.000000   
..        ...       ...       ...       ...     ...          ...       ...   
995  0.000000  0.000000  0.000000  0.000000     0.0          0.0  0.000000   
996  0.204745  0.000000  0.000000  0.000000     0.0          0.0  0.000000   
997  0.000000  0.181842  0.181842  0.181842     0.0          0.0  0.000000   
998  0.000000  0.000000  0.000000  0.000000     0.0          0.0  0.000000   
999  0.204745  0.000000  0.000000  0.000000     0.0          0.0  0.000000   

        vivía  
0    0.000000  
1    0.000000  
2    0.000000  
3    0.000000  
4    0.000000  
..        ...  
995  0.000000  
996  0.000000  
997  0.000000  
998  0.197887  
999  0.000000  

[1000 rows x 143 columns]

In [95]:
# variable ordinal
label_codificador_ordinal = preprocessing.LabelEncoder()
datos_procesados['col_ordinal'] = label_codificador_ordinal.fit_transform(datos.col_ordinal)
datos_procesados['col_ordinal']

0      2
1      4
2      3
3      1
4      0
      ..
995    3
996    2
997    4
998    0
999    4
Name: col_ordinal, Length: 1000, dtype: int32